# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b5927ca0122acd3c42c03d8c764f25d384211d009ef2e052afd861e4840354a0da6219ebc4b1d8ebfce4e4c9aaaa714c938968cc5ebea9f92b0d558da04e391d

test:
  secret_key_base: 6339ebfba6c883aabf6659c72c1060da14aca8cd28de5c7b4403dd680d0db010834d97e1b88b1ddb6051035257f9d95f1d9b3ceb3372b24721af051fe8a2bb0a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
